# Generated by Django 4.0.4 on 2022-07-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('opt1', models.CharField(max_length=100)),
                ('opt2', models.CharField(max_length=100)),
                ('opt3', models.CharField(max_length=100)),
                ('opt4', models.CharField(max_length=100)),
                ('opt1_cnt', models.IntegerField(default=0)),
                ('opt2_cnt', models.IntegerField(default=0)),
                ('opt3_cnt', models.IntegerField(default=0)),
                ('opt4_cnt', models.IntegerField(default=0)),
            ],
        ),
    ]
