# Generated by Django 4.0.4 on 2022-07-07 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollApp', '0002_voters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voters',
            old_name='voter',
            new_name='vote_id',
        ),
    ]
