# Generated by Django 4.0.4 on 2022-07-07 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollApp', '0003_rename_voter_voters_vote_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Voters',
            new_name='Voter',
        ),
    ]
